/**
 * Project Auro - Governance Document Pack and Sprint Backlog Exporter
 * 
 * Supports exporting:
 * 1. Single Markdown or combined Markdown bundle
 * 2. ZIP archive of all 12 governance documents
 * 3. Printable PDF-ready formatted document (or PDF binary)
 * 4. DOCX document
 * 5. Sprint Backlog CSV
 * 6. Jira-importable Sprint CSV (Summary, Issue Type, Description, Priority, Story Points, Acceptance Criteria)
 * 7. Sprint Backlog XLSX (XML-based spreadsheet)
 */

import {
  GOVERNANCE_DOCUMENT_KINDS,
  GOVERNANCE_DOC_DEFINITIONS,
  type GovernanceDocumentKind,
} from "./governance-documents.js";
import zlib from "node:zlib";

export interface SprintStoryItem {
  id: string;
  epic: string;
  summary: string;
  issueType: "Story" | "Task" | "Bug" | "Epic";
  description: string;
  priority: "Highest" | "High" | "Medium" | "Low";
  storyPoints: number;
  acceptanceCriteria: string;
  assigneeRole: string;
  dependsOn?: string;
}

export const DEFAULT_SPRINT_STORIES: SprintStoryItem[] = [
  {
    id: "US-101",
    epic: "Core Platform",
    summary: "Project Kickoff Wizard & Brief Capture",
    issueType: "Story",
    description: "Capture project parameters, team constraints, and trigger autonomous governance orchestration.",
    priority: "High",
    storyPoints: 5,
    acceptanceCriteria: "Form validation passes; creates company goal and kickoff issue.",
    assigneeRole: "PM / Frontend",
    dependsOn: "None",
  },
  {
    id: "US-102",
    epic: "Governance Engine",
    summary: "12-Document Pack Generation & Validator",
    issueType: "Story",
    description: "Implement section validator and template generator for all 12 canonical governance documents.",
    priority: "High",
    storyPoints: 8,
    acceptanceCriteria: "All 12 documents pass section validator; rejection on missing required sections.",
    assigneeRole: "CTO / Backend",
    dependsOn: "US-101",
  },
  {
    id: "US-103",
    epic: "Governance Engine",
    summary: "Cross-Agent Review Loops & CEO Approval Gate",
    issueType: "Story",
    description: "Orchestrate dependency DAG (PM -> Security -> CTO -> DevOps -> QA -> CEO) and record review comments.",
    priority: "High",
    storyPoints: 5,
    acceptanceCriteria: "Reviews posted on task threads; CEO approval seals the pack.",
    assigneeRole: "CEO / PM",
    dependsOn: "US-102",
  },
  {
    id: "US-104",
    epic: "Document Center",
    summary: "Document Center UI with Version Diff and Markdown Editor",
    issueType: "Story",
    description: "Build token-gated UI for editing documents, viewing version diffs, and triggering exports.",
    priority: "Medium",
    storyPoints: 8,
    acceptanceCriteria: "Green Auro theme, 0 token gate violations, version diff rendering.",
    assigneeRole: "Frontend Lead",
    dependsOn: "US-102",
  },
  {
    id: "US-105",
    epic: "Document Center",
    summary: "Multi-format Exporters (PDF, DOCX, ZIP, CSV, Jira, XLSX)",
    issueType: "Story",
    description: "Generate compliant export files for all document packs and sprint backlog formats.",
    priority: "Medium",
    storyPoints: 5,
    acceptanceCriteria: "Exports contain accurate metadata and pass content verification tests.",
    assigneeRole: "DevOps / Backend",
    dependsOn: "US-104",
  },
  {
    id: "US-106",
    epic: "Security & QA",
    summary: "STRIDE Threat Audit and Sandbox Confinement Testing",
    issueType: "Story",
    description: "Automate test suite proving Bubblewrap sandbox confinement and AES-256-GCM secret encryption.",
    priority: "High",
    storyPoints: 5,
    acceptanceCriteria: "100% pass on security and sandbox policy test suites.",
    assigneeRole: "Security / QA",
    dependsOn: "US-102",
  },
];

/**
 * Generates combined single-file Markdown bundle.
 */
export function exportCombinedMarkdown(
  projectName: string,
  documents: Record<string, { title: string; fileName: string; content: string }>,
): string {
  const parts: string[] = [
    `# Complete Project Governance Pack: ${projectName}`,
    `*Generated by Project Auro autonomous governance control plane*\n`,
    `---\n`,
  ];

  for (const [kind, doc] of Object.entries(documents)) {
    parts.push(`<!-- START DOCUMENT: ${doc.fileName} (${kind}) -->`);
    parts.push(doc.content.trim());
    parts.push(`\n---\n`);
  }

  return parts.join("\n");
}

/**
 * Escapes CSV values with double quotes and comma handling.
 */
function escapeCsv(value: string | number | undefined | null): string {
  if (value === undefined || value === null) return '""';
  const str = String(value).replace(/"/g, '""');
  return `"${str}"`;
}

/**
 * Generates Standard Sprint Backlog CSV.
 */
export function exportSprintBacklogCsv(stories: SprintStoryItem[] = DEFAULT_SPRINT_STORIES): string {
  const headers = [
    "ID",
    "Epic",
    "Summary",
    "Issue Type",
    "Priority",
    "Story Points",
    "Assignee Role",
    "Depends On",
    "Description",
    "Acceptance Criteria",
  ];

  const rows = [headers.join(",")];

  for (const story of stories) {
    const row = [
      escapeCsv(story.id),
      escapeCsv(story.epic),
      escapeCsv(story.summary),
      escapeCsv(story.issueType),
      escapeCsv(story.priority),
      story.storyPoints,
      escapeCsv(story.assigneeRole),
      escapeCsv(story.dependsOn || "None"),
      escapeCsv(story.description),
      escapeCsv(story.acceptanceCriteria),
    ];
    rows.push(row.join(","));
  }

  return rows.join("\n");
}

/**
 * Generates Jira-importable CSV format.
 */
export function exportJiraImportCsv(
  projectName: string,
  stories: SprintStoryItem[] = DEFAULT_SPRINT_STORIES,
): string {
  const headers = [
    "Issue Key",
    "Issue Type",
    "Summary",
    "Description",
    "Priority",
    "Story Points",
    "Epic Name",
    "Acceptance Criteria",
    "Custom field (Project)",
  ];

  const rows = [headers.join(",")];

  for (const story of stories) {
    const row = [
      escapeCsv(story.id),
      escapeCsv(story.issueType),
      escapeCsv(story.summary),
      escapeCsv(story.description),
      escapeCsv(story.priority),
      story.storyPoints,
      escapeCsv(story.epic),
      escapeCsv(story.acceptanceCriteria),
      escapeCsv(projectName),
    ];
    rows.push(row.join(","));
  }

  return rows.join("\n");
}

/**
 * Generates Spreadsheet XML (XLSX/XML 2003) format readable by Microsoft Excel and LibreOffice.
 */
export function exportSprintBacklogXlsx(
  projectName: string,
  stories: SprintStoryItem[] = DEFAULT_SPRINT_STORIES,
): string {
  const rowsXml = stories
    .map(
      (s) => `      <Row>
        <Cell><Data ss:Type="String">${escapeXml(s.id)}</Data></Cell>
        <Cell><Data ss:Type="String">${escapeXml(s.epic)}</Data></Cell>
        <Cell><Data ss:Type="String">${escapeXml(s.summary)}</Data></Cell>
        <Cell><Data ss:Type="String">${escapeXml(s.issueType)}</Data></Cell>
        <Cell><Data ss:Type="String">${escapeXml(s.priority)}</Data></Cell>
        <Cell><Data ss:Type="Number">${s.storyPoints}</Data></Cell>
        <Cell><Data ss:Type="String">${escapeXml(s.assigneeRole)}</Data></Cell>
        <Cell><Data ss:Type="String">${escapeXml(s.description)}</Data></Cell>
        <Cell><Data ss:Type="String">${escapeXml(s.acceptanceCriteria)}</Data></Cell>
      </Row>`,
    )
    .join("\n");

  return `<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">
  <Worksheet ss:Name="Sprint Backlog - ${escapeXml(projectName)}">
    <Table>
      <Row ss:StyleID="Header">
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Epic</Data></Cell>
        <Cell><Data ss:Type="String">Summary</Data></Cell>
        <Cell><Data ss:Type="String">Issue Type</Data></Cell>
        <Cell><Data ss:Type="String">Priority</Data></Cell>
        <Cell><Data ss:Type="String">Story Points</Data></Cell>
        <Cell><Data ss:Type="String">Assignee</Data></Cell>
        <Cell><Data ss:Type="String">Description</Data></Cell>
        <Cell><Data ss:Type="String">Acceptance Criteria</Data></Cell>
      </Row>
${rowsXml}
    </Table>
  </Worksheet>
</Workbook>`;
}

function escapeXml(unsafe: string): string {
  return unsafe
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

/**
 * Simple ZIP file writer using Node's built-in zlib for zero extra dependencies.
 * Creates a compliant PKZip archive from a map of file names to string contents.
 */
export function exportZipArchive(files: Record<string, string>): Buffer {
  const fileEntries: Array<{ name: string; buffer: Buffer; compressed: Buffer; crc: number }> = [];

  for (const [name, content] of Object.entries(files)) {
    const rawBuffer = Buffer.from(content, "utf8");
    const compressed = zlib.deflateRawSync(rawBuffer);
    const crc = crc32(rawBuffer);
    fileEntries.push({ name, buffer: rawBuffer, compressed, crc });
  }

  const localHeaders: Buffer[] = [];
  const centralHeaders: Buffer[] = [];
  let offset = 0;

  for (const entry of fileEntries) {
    const nameBuffer = Buffer.from(entry.name, "utf8");
    const localHeader = Buffer.alloc(30 + nameBuffer.length);
    localHeader.writeUInt32LE(0x04034b50, 0); // Local file header signature
    localHeader.writeUInt16LE(20, 4);        // Version needed
    localHeader.writeUInt16LE(0, 6);         // General purpose bit flag
    localHeader.writeUInt16LE(8, 8);         // Compression method (deflate)
    localHeader.writeUInt16LE(0, 10);        // Last mod file time
    localHeader.writeUInt16LE(0, 12);        // Last mod file date
    localHeader.writeUInt32LE(entry.crc, 14); // CRC-32
    localHeader.writeUInt32LE(entry.compressed.length, 18); // Compressed size
    localHeader.writeUInt32LE(entry.buffer.length, 22);     // Uncompressed size
    localHeader.writeUInt16LE(nameBuffer.length, 26);       // File name length
    localHeader.writeUInt16LE(0, 28);                       // Extra field length
    nameBuffer.copy(localHeader, 30);

    const centralHeader = Buffer.alloc(46 + nameBuffer.length);
    centralHeader.writeUInt32LE(0x02014b50, 0); // Central directory header signature
    centralHeader.writeUInt16LE(20, 4);         // Version made by
    centralHeader.writeUInt16LE(20, 6);         // Version needed
    centralHeader.writeUInt16LE(0, 8);          // Bit flag
    centralHeader.writeUInt16LE(8, 10);         // Compression method
    centralHeader.writeUInt16LE(0, 12);         // Mod time
    centralHeader.writeUInt16LE(0, 14);         // Mod date
    centralHeader.writeUInt32LE(entry.crc, 16); // CRC-32
    centralHeader.writeUInt32LE(entry.compressed.length, 20); // Compressed size
    centralHeader.writeUInt32LE(entry.buffer.length, 24);     // Uncompressed size
    centralHeader.writeUInt16LE(nameBuffer.length, 28);       // File name length
    centralHeader.writeUInt16LE(0, 30);                       // Extra field length
    centralHeader.writeUInt16LE(0, 32);                       // File comment length
    centralHeader.writeUInt16LE(0, 34);                       // Disk number start
    centralHeader.writeUInt16LE(0, 36);                       // Internal file attributes
    centralHeader.writeUInt32LE(0, 38);                       // External file attributes
    centralHeader.writeUInt32LE(offset, 42);                  // Relative offset of local header
    nameBuffer.copy(centralHeader, 46);

    localHeaders.push(localHeader, entry.compressed);
    centralHeaders.push(centralHeader);

    offset += localHeader.length + entry.compressed.length;
  }

  const centralDirOffset = offset;
  let centralDirSize = 0;
  for (const ch of centralHeaders) {
    centralDirSize += ch.length;
  }

  const endRecord = Buffer.alloc(22);
  endRecord.writeUInt32LE(0x06054b50, 0); // End of central dir signature
  endRecord.writeUInt16LE(0, 4);          // Number of this disk
  endRecord.writeUInt16LE(0, 6);          // Disk where central dir starts
  endRecord.writeUInt16LE(fileEntries.length, 8);  // Number of central dir records on this disk
  endRecord.writeUInt16LE(fileEntries.length, 10); // Total number of central dir records
  endRecord.writeUInt32LE(centralDirSize, 12);     // Size of central directory
  endRecord.writeUInt32LE(centralDirOffset, 16);   // Offset of start of central directory
  endRecord.writeUInt16LE(0, 20);                  // Comment length

  return Buffer.concat([...localHeaders, ...centralHeaders, endRecord]);
}

/**
 * Computes standard CRC-32 checksum for zip header integrity.
 */
function crc32(buf: Buffer): number {
  let crc = 0 ^ -1;
  for (let i = 0; i < buf.length; i++) {
    crc = (crc >>> 8) ^ CRC_TABLE[(crc ^ buf[i]) & 0xff];
  }
  return (crc ^ -1) >>> 0;
}

const CRC_TABLE = new Uint32Array(256);
for (let i = 0; i < 256; i++) {
  let c = i;
  for (let k = 0; k < 8; k++) {
    c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  }
  CRC_TABLE[i] = c >>> 0;
}

/**
 * Generates DOCX package (OOXML ZIP containing word/document.xml).
 */
export function exportDocx(
  projectName: string,
  documents: Record<string, { title: string; fileName: string; content: string }>,
): Buffer {
  const docXmlParts: string[] = [
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`,
    `<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">`,
    `<w:body>`,
    `<w:p><w:pPr><w:pStyle w:val="Title"/></w:pPr><w:r><w:t>${escapeXml(projectName)} - Governance Pack</w:t></w:r></w:p>`,
  ];

  for (const doc of Object.values(documents)) {
    docXmlParts.push(
      `<w:p><w:pPr><w:pStyle w:val="Heading1"/></w:pPr><w:r><w:t>${escapeXml(doc.title)} (${escapeXml(doc.fileName)})</w:t></w:r></w:p>`,
    );
    const paragraphs = doc.content.split(/\r?\n\r?\n/);
    for (const para of paragraphs) {
      if (para.trim()) {
        docXmlParts.push(`<w:p><w:r><w:t>${escapeXml(para.trim())}</w:t></w:r></w:p>`);
      }
    }
  }

  docXmlParts.push(`</w:body></w:document>`);
  const documentXml = docXmlParts.join("\n");

  const contentTypesXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>`;

  const relsXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>`;

  return exportZipArchive({
    "[Content_Types].xml": contentTypesXml,
    "_rels/.rels": relsXml,
    "word/document.xml": documentXml,
  });
}

/**
 * Generates valid PDF file buffer for the governance pack.
 */
export function exportPdf(
  projectName: string,
  documents: Record<string, { title: string; fileName: string; content: string }>,
): Buffer {
  const textLines: string[] = [
    `Project Auro - Governance Document Pack`,
    `Project: ${projectName}`,
    `Status: APPROVED by CEO`,
    `Total Documents: ${Object.keys(documents).length}`,
    `----------------------------------------------------`,
  ];

  for (const doc of Object.values(documents)) {
    textLines.push(`\n=== ${doc.title} (${doc.fileName}) ===\n`);
    const preview = doc.content.slice(0, 300).replace(/\r?\n/g, " ");
    textLines.push(preview + "...");
  }

  const streamContent = `BT\n/F1 12 Tf\n50 750 Td\n14 TL\n` +
    textLines.map((line) => `(${escapePdfString(line)}) '`).join("\n") +
    `\nET`;

  const streamLength = Buffer.byteLength(streamContent);

  const pdfTemplate = `%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>
endobj
4 0 obj
<< /Length ${streamLength} >>
stream
${streamContent}
endstream
endobj
5 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>
endobj
xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000234 00000 n 
0000000${(300 + streamLength).toString().padStart(3, "0")} 00000 n 
trailer
<< /Size 6 /Root 1 0 R >>
startxref
${400 + streamLength}
%%EOF`;

  return Buffer.from(pdfTemplate, "utf8");
}

function escapePdfString(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}
